services:
  postgres:
    image: postgres:16
    container_name: sac-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: sac_db
      POSTGRES_USER: sac_user
      POSTGRES_PASSWORD: sac_password

    volumes:
      - sac_pgdata:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sac_user -d sac_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  sac_pgdata:
    driver: local